name:                TestMatch
version:             0.1.0.0
github:              "eggplantbren/TestMatch"
license:             MIT
author:              "Brendon J. Brewer"
maintainer:          "brendon.brewer@gmail.com"
copyright:           "Brendon J. Brewer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eggplantbren/TestMatch#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wextra
  dependencies:
    - mwc-random
    - primitive
    - text
    - vector

executables:
  Main:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wextra
    dependencies:
    - TestMatch
    - text
    - vector

tests:
  TestMatch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TestMatch
